Project Boilerplate {
  database_type: 'PostgreSQL'
  Note: '''
    # Boilerplate Database
    **This is boilerplate database documentation**
  '''
}

Table users {
  id integer [primary key]
  createdAt timestamp [not null]
  updatedAt timestamp [not null]
  deletedAt timestamp
  email varchar [not null , unique]
  password varchar [not null]
  name varchar
  // roles integer [ref:<> roles.id]
}

Table roles {
  id integer [primary key]
  createdAt timestamp [not null]
  updatedAt timestamp [not null]
  deletedAt timestamp
  name varchar [not null , unique]
  description varchar
  // permissions integer [ref:<> permissions.id]
}

Table permissions {
  id integer [primary key]
  createdAt timestamp [not null]
  updatedAt timestamp [not null]
  deletedAt timestamp
  name varchar [ unique]
  description varchar
}

Table roles_permissions_permissions{
  rolesId integer [ref: > roles.id]
  permissionId integer [ref: > permissions.id]
}

Table users_roles_roles{
  rolesId integer [ref: > roles.id]
  usersId integer [ref: > users.id]
}
