# docker-compose.yml
version: '3'
services:
  postgres:
    container_name: sale-system-backend-${NODE_ENV}-db-postgres
    image: "postgres"
    restart: always
    networks:
      - sale-system-backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_EXPOSE_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
  redis:
    container_name: sale-system-backend-${NODE_ENV}-db-redis
    image: redis
    restart: always
    networks:
      - sale-system-backend
    volumes:
      - redis:/data
    ports:
      - "${REDIS_EXPOSE_PORT}:${REDIS_PORT}"
  main:
    build:
      context: .
      target: ${NODE_ENV}
      dockerfile: Dockerfile
    container_name: sale-system-backend-${NODE_ENV}-app-main
    restart: always
    networks:
      - sale-system-backend
    depends_on:
      - postgres
      - redis
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/opt/app
networks:
  sale-system-backend:
volumes:
  postgres:
  redis:

